# Generated by Django 2.2.5 on 2021-09-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteleInfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='姓名')),
                ('card', models.CharField(max_length=20, verbose_name='身份证号')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
            },
        ),
    ]
