# Generated by Django 2.2.5 on 2021-08-31 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZXWL', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicdetail',
            name='cover',
        ),
    ]
